name: Build CSV on JSON changes

on:
  push:
    paths:
      - '**/*.json'

jobs:
  build-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Python script
      run: python generate_dataset_overview.py
    
    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-csv
        path: overview_available_datasets.csv

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: generated-csv
        path: downloaded-csv

    - name: Configure Git
      run: |
        git config --global user.email "actions-bot@example.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Commit CSV file
      run: |
        git add downloaded-csv/overview_available_datasets.csv
        git commit -m "Add generated CSV file"
        git push
